version: '3.8'

services:
  # https://hub.docker.com/_/redmine
  redmine:
    container_name: 'redmine'
    image: redmine:latest
    restart: always
    volumes:
      - ./redmine-plugins:/usr/src/redmine/plugins
      - ./redmine-themes:/usr/src/redmine/public/themes
      - ./redmine-data:/usr/src/redmine/files
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: 
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: 
      REDMINE_PLUGINS_MIGRATE: "true"

